CREATE TABLE OLIVE_VARIETY( 
    ID BIGINT NOT NULL, 
    DESCRIPTION VARCHAR(255) NOT NULL, 
    XKEY VARCHAR(255) NOT NULL 
);
ALTER TABLE OLIVE_VARIETY ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);

CREATE CACHED TABLE TICKET( 
    ID BIGINT NOT NULL, 
    DATE_OF_TICKET DATE NOT NULL, 
    WEIGHT BIGINT NOT NULL, 
    OLIVE_VARIETY BIGINT 
);
ALTER TABLE TICKET ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY(ID);

ALTER TABLE OLIVE_VARIETY ADD CONSTRAINT UK_14WEA7CCCRV3D1G594PB9Y8EV UNIQUE(XKEY);
